name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          scope: '@bilyk-alexander'

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Install dependencies
        run: npm ci

      # - name: 'Bump version'
      #   uses: 'phips28/gh-action-bump-version@master'
      #   with:
      #     tag-prefix: 'v'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish to the registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

